# .github/workflows/types.yml
name: Type Check

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

jobs:
  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run types
